.PHONY : client server clean

all:
	gcc -o server server.c
	gcc -o client client.c

server:	
	gcc -o server server.c

client:
	gcc -o client client.c

clean:
	rm -rf server
	rm -rf client
